# Generated by Django 4.1.3 on 2022-11-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_topic', models.CharField(help_text='Topico do post', max_length=300)),
                ('post_content', models.CharField(help_text='Conteudo do post', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(help_text='Entre com o username', max_length=20, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Informe o Email', max_length=254)),
            ],
        ),
    ]
